apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-dep
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-dep-pod
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - name: nginxport
          containerPort: 80

